language: go
go_import_path: github.com/dariodip/prefix-search
go:
  - "1.9.2"
install:
  - go get -t ./...
script:
  - go test ./...

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/75abaea342c923373ac3  # gitter
    on_success: change
    on_failure: always
    on_start: never
